name: btp_multi_sector
description: Application mobile multi-secteurs d'activités (BTP, Agribusiness, Mining, Divers)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  rive: ^0.12.4
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3
  mapbox_gl: ^0.16.0
  
  # Camera & Media
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  photo_view: ^0.14.0
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  
  # Authentication & Security
  local_auth: ^2.1.7
  crypto: ^3.0.3
  
  # Payments
  stripe_payment: ^1.1.4
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  # syncfusion_flutter_charts: ^23.2.7
  
  # Forms & Validation
  # form_builder_validators: ^9.1.0
  # flutter_form_builder: ^9.1.1
  
  # Animations
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.8
  
  # QR Code & Barcode
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
